POST http://localhost:4000/posts/new
Content-Type: application/json

{
    "postContent": "Test med rest"
}

###

GET http://localhost:4000/posts

###

PATCH http://localhost:4000/posts/1
Content-Type: application/json

{
    "postContent": "Testar uppdatera med rest"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "userName": "admin",
    "password": "admin"
}